### ISSUE TITLE
Apps init slugify error

### ISSUE THREAD

**Issue by JoshuaUrrutia** [TACC-Cloud/tapis-cli#332]
**Describe the bug**
One of the arguments passed to slugify during apps init is off

**To Reproduce**
```
urrutia$ tapis apps init test_app
slugify() got an unexpected keyword argument 'separator'
```
Same issue with more descriptive arguments:
```
 tapis apps init --app-label classifier --app-description "Image classifier" --app-version 0.0.1 classifier_app
```

**Expected behavior**
Initialize a slugify-ed app directory

**Desktop (please complete the following information):**
 - OS: macOS
 - Version 10.14.6

**Comment by JoshuaUrrutia** [comment]
More info:
```
urrutia$ pip freeze | grep slugify
python-slugify==4.0.0
unicode-slugify==0.1.5
```

https://github.com/TACC-Cloud/tapis-cli/blob/main/tapis_cli/commands/taccapis/v2/apps/init/init.py#L126

**Comment by johnfonner** [comment]
After digging into this a bit, it turns out this is an interesting bug.  There are 3 PyPI projects that all try to install into the same directory name. `python-slugify`,`unicode-slugify`, and `awesome-slugify`.  They break convention of matching the module name to the project name.  From my testing, if you install more than one into the same library path (e.g. `pip install --user` for both), the second module installed will clobber and break the first.  The pip command has no qualms with this and does not raise an error.  So @JoshuaUrrutia, there is a good chance that python-slugify is broken in your environment.

There is an open issue for `unicode-slugify` on this exact thing: https://github.com/mozilla/unicode-slugify/issues/27.  It looks like Mozilla is not updating their module anymore, though.

So we may be able to code more defensively now that you raised the conflict.  That will be our ideal solution: just make it work even if the modules are messed up.  The source of the problem is upstream of tapis-cli, though, so it doesn't look like there is a perfect solution that we can implement if we depend on any of those 3 conflicting modules.
